### ISSUE TITLE
Genaral feedback from the users

### ISSUE THREAD

**Issue by Maarscomics** [AlgoWorldNFT/algoworld-swapper#100]
I have gradually switches some swaps that I use the most from old swapper to new one and I get a lot of issues reported by the users.

The general issue is mostly from the first click on the link that leads to a swap. 
Most people  just get this situation 
![image](https://user-images.githubusercontent.com/96620717/180777771-67ca6c4a-9512-4f2c-a8e9-d511ec76689e.png)

they feel that the swap is empty.

Then I have to explain the they first need to connect wallet at switch to mainnet. 

after they do that they need to go back to the link and enter the screen again
some people get this situation even tho the swap is active and had assets and funds

![image](https://user-images.githubusercontent.com/96620717/180778061-774e9cdb-7776-4ce4-b1bd-ad62316f7c63.png)

then they need to try and follow link to a swap again and it might work or not.

I feel there is some issue with entering swapper for the first time or when your wallet is not connected.

**Comment by aorumbayev** [comment]
@Maarscomics should be addressed by this pr https://github.com/AlgoWorldNFT/algoworld-swapper/pull/102

one requirement from your side is to regenerate the share url that now explicitly appends mainnet as query param. Please give it a try and reopen if there are issues
