### ISSUE TITLE
Feedback - some minor upgrades

### ISSUE THREAD

**Issue by Maarscomics** [AlgoWorldNFT/algoworld-swapper#101]
I have few things that I miss from v1 of swapper.

1. there is no disable swap button. If I want to disable it but keep my link and just enable it later I dont have that option yer. I can delete it but then I have to do whole new swap.

2. v1 of swapper had this nice option where I would send multiple assets to the address and when I opened the swap screen I could see how many assets is there left. I can then track how many there is left in the swapper.

![image](https://user-images.githubusercontent.com/96620717/180779075-db6c55cd-465a-497c-b457-72a1ec33aefa.png)

**Comment by aorumbayev** [comment]
Addressed in v0.5.0 @Maarscomics
