### ISSUE TITLE
Overwriting of swaps between same ASAs

### ISSUE THREAD

**Issue by LuzzHub** [AlgoWorldNFT/algoworld-swapper#136]
I have created 5 public swaps between asa 978590908 and AWT (233939122):

- 1 card - 200 AWT
- 1 card - 225 AWT
- 1 card - 250 AWT
- 1 card - 275 AWT
- 1 card - 300 AWT

However, the only one showing both on public swaps and in My Swaps is the last one for 300 AWT. [All transactions and fees for swaps went through](https://algoexplorer.io/address/6CZNVPUSXFBXIZ3GKVTOLZMSGCUR36ZRDK3FQH35W53GBE7JDZHWJBQPIU) (blocks [25634034](https://algoexplorer.io/block/25634034) to [25634106](https://algoexplorer.io/block/25634106))

**Comment by aorumbayev** [comment]
@LuzzHub i just merged a hotfix that should allow you to display swaps not present in swap configuration, can confirm that it will work for you address after its deployed in next 10-15 mins. You can then deactivate missing swaps and recreate them - will have a proper fix later after further debugging. Sorry for inconvenience

**Comment by aorumbayev** [comment]
<img width="914" alt="Screenshot 2022-12-18 at 15 32 55" src="https://user-images.githubusercontent.com/7698600/208304253-2236ed65-a863-4441-a3fa-8289ca26ecc0.png">

**Comment by aorumbayev** [comment]
Please close issue once you confirm it worked

**Comment by LuzzHub** [comment]
Thank you for taking care of this. I was able to deactivate all those swaps.
