### ISSUE TITLE
Swap not working

### ISSUE THREAD

**Issue by rcraig66** [AlgoWorldNFT/algoworld-swapper#159]
I tried to perform the swap below.  After I hit Perform Swap there was a pop-up with Cancel an Proceed buttons.  I clicked Proceed and nothing happened either in my mobile Pera wallet or on the swapper website.  I tried several times and nothing happened.

https://swapper.algoworld.io/swap/YQ5WBAKR4URERNO7SJWX2M7ERN4FGGN3SLOSZHYAYNW3BLN7FNOEV2JYLY/4AAOHDNQSOQBCM4SYELDNDIGH4RBPHYP2MHUZJ4HTADM5VV55GI5DL47ZU?chain=mainnet

**Comment by aorumbayev** [comment]
@rcraig66 tested on Androind, iOS and Desktop with Pera on MainNet. All work without issues. Likely Pera or walletconnect related bugs that occur often. Please make sure to clear cache in your browser, reconnect your wallet provider and try again. Don't see any issues on swapper code side. Closing
