### ISSUE TITLE
Swaps won't display on "My Swaps" page

### ISSUE THREAD

**Issue by MattAlgoworld** [AlgoWorldNFT/algoworld-swapper#165]
Hey Al. Unfortunately the swaps from the Build Manager Wallet won't display on "My Swaps" page. See the screenshot attached. The public address is 75BMV3IXUMULXWV4JCCEET3OXZQU5J32J5CZ62A4DOH4HHF3KTFFX56ZZQ. 
Same problem on mobile and Desktop (both Safari and Chrome). I also changed to IPFS provider, with no effect on the result. Thanks for your help!
![Capture d’écran 2023-05-21 à 20 39 59](https://github.com/AlgoWorldNFT/algoworld-swapper/assets/84573579/4195e7d5-afea-45ed-a97d-d1010ddef218)

**Comment by aorumbayev** [comment]
@MattAlgoworld have you tried with show detailed history enabled ?

**Comment by MattAlgoworld** [comment]
Yes, that doesn't change anything :( I also tried with both Pera and Defly wallets.

**Comment by aorumbayev** [comment]
Fixed in https://github.com/AlgoWorldNFT/algoworld-swapper/releases/tag/v1.0.2
