### ISSUE TITLE
Fix bug in UI chain type switcher

### ISSUE THREAD

**Issue by Maarscomics** [AlgoWorldNFT/algoworld-swapper#59]
Im just writing from some user feedback. The switch between mainnet and testnet is bit confusing. 

it would either be better to put MainNet title insted of testnet. Or just have testnet activate when the slider is moved right and it turns green,

![image](https://user-images.githubusercontent.com/96620717/173426028-7862c717-b6a4-43c4-bf3f-954e412b438e.png)

the way people think it works is that when you move slider right and it goes green it should activate testnet

**Comment by aorumbayev** [comment]
@Maarscomics fixed in https://github.com/AlgoWorldNFT/algoworld-swapper/pull/61 - thank for the feedback! :-)
