### ISSUE TITLE
Incentive fee sender

### ISSUE THREAD

**Issue by cusma** [AlgoWorldNFT/algoworld-swapper#7]
https://github.com/AlgoWorldNFT/algoworld-swapper/blob/705d1d2c7fb554e1723711b0ed09b664ad74ffa0/src/algoworldswapper.py#L124

This is not a critical check, but should the contract enforce also that:
```python
Gtxn[INCENTIVE_FEE].sender() == Gtxn[REQUESTED_ASA_XFER].sender()
```
Otherwise any account could potentially pay for the incentive fee (which is not dangerous for swapper users).

**Comment by aorumbayev** [comment]
Hey thanks for opening the issue @cusma. 
So to recap, you are suggesting to add the:
```
Gtxn[INCENTIVE_FEE].sender() == Gtxn[REQUESTED_ASA_XFER].sender()
``` to `asa_swap` function?

Also not sure what you mean by the:
```
Gtxn[INCENTIVE_FEE].receiver() == Addr(INCENTIVE_FEE_ADDRESS),
```
not being critical, from the incentive receiver's perspective, how else would he be sure that contract verifies that his wallet is correctly specified in fee transaction? Wouldn't removing this mean that anyone could send the incentive anywhere they want?

**Comment by cusma** [comment]
@aorumbayev I'm not suggesting to remove the following one:
```python
Gtxn[INCENTIVE_FEE].receiver() == Addr(INCENTIVE_FEE_ADDRESS),
```

I was just reporting [#L124](https://github.com/AlgoWorldNFT/algoworld-swapper/blob/705d1d2c7fb554e1723711b0ed09b664ad74ffa0/src/algoworldswapper.py#L124) as a reference, to add:
```python
Gtxn[INCENTIVE_FEE].sender() == Gtxn[REQUESTED_ASA_XFER].sender()
```
right after this line, as additional check in `asa_swap`.

**Comment by aorumbayev** [comment]
@cusma the pr above addresses it
