### ISSUE TITLE
Swap not loading

### ISSUE THREAD

**Issue by mjjones1** [AlgoWorldNFT/algoworld-swapper#70]
https://swapper.algoworld.io/swap/7GHPEXDUFLP5ZGAFSRAWQNQEV3BKOXDB63KO6Z4YROIXA5JSL3TVNPMCWI/YJSR2I5QU7H4TCALVRVGAUIZQNJ5JZB2WYWBCCH6WWNDWAJ2SOFA3N3FLE

The card is in the escrow account so the swap is still active (at time of writing): https://algoexplorer.io/address/YJSR2I5QU7H4TCALVRVGAUIZQNJ5JZB2WYWBCCH6WWNDWAJ2SOFA3N3FLE

Same problem on both:
- Mobile: Samsung Browser / Pera Wallet
- PC: Edge Browser / MyAlgo Wallet

My wallet is connected on mainnet
- 'You provide' box is empty
- 'You receive' box is empty
- 'CLICK TO RETRY LOADING' box. Clicking it results in very brief 'Loading, please wait' box then returns to 'CLICK TO RETRY LOADING' box

I successfully made a swap ~10 days ago on mobile

**Comment by mjjones1** [comment]
Using dev tools on Edge browser, I get a 404 on 'CLICK TO RETRY LOADING'

General:
Request URL: https://mainnet-idx.algonode.cloud/v2/accounts/7GHPEXDUFLP5ZGAFSRAWQNQEV3BKOXDB63KO6Z4YROIXA5JSL3TVNPMCWI
Request Method: GET
Status Code: 404 
Remote Address: 104.26.3.248:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
access-control-allow-origin: *
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 71ff87fb0fd37dea-LAX
content-encoding: gzip
content-type: application/json; charset=UTF-8
date: Thu, 23 Jun 2022 19:11:43 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=2NWrlm85javeqsaOjrZfwTr9o8wKU9xaXSAKL8URWpWDlfkUA7EXBd6GDBY7vH%2BYlyIky92JpBzGwOvOn8RroZOS72xjIkWe7nhyuvjeYVhhglg8HF78%2BVuQB%2BDAwHpCXd%2FdxGE5QldSypqR"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Origin

Request Headers:
:authority: mainnet-idx.algonode.cloud
:method: GET
:path: /v2/accounts/7GHPEXDUFLP5ZGAFSRAWQNQEV3BKOXDB63KO6Z4YROIXA5JSL3TVNPMCWI
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
origin: https://swapper.algoworld.io
referer: https://swapper.algoworld.io/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Microsoft Edge";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
x-indexer-api-token

**Comment by aorumbayev** [comment]
@mjjones1 so looks like root cause was a networking error, either related to your internet provider or recent cloudflare outage. Will close for now unless new reports with similar issue popup
